### ISSUE TITLE
Topic /dock publishing invalid type robot_create_msgs::msg::Dock instead of DockStatus

### ISSUE THREAD

**Issue by carTloyal123** [iRobotEducation/irobot_create_msgs#14]
## Bug report

**Required Info:**

- Operating System:
  - OS: Ubuntu 20.04
- Installation type:
  - Binaries and from Source
- Version or commit hash:
  - release
- DDS implementation:
  - Fast, and Cyclone using ROS2 Humble/Galactic
- Client library (if applicable):
  - 

#### Steps to reproduce issue

On ROS2 Humble while connected to Create3 (eth/wifi)
```
ros2 topic echo /dock
```

#### Expected behavior
/dock topic echos as normal showing the information about the docking status
#### Actual behavior
undefined message type error 
#### Additional information
I see that the dock message has changed from galactic to humble so I just wanted to put in an issue so that this change can be documented in the Create3 ROS2 setup documentation. In the installation instructions for ROS2 humble on a client, it could be noted that some messages will be incompatible. Thanks!

**Comment by shamlian** [comment]
To verify -- is your Create 3 running Galactic (G.x.x) or Humble (H.x.x) firmware?
How have you installed ROS 2 Humble on your Ubuntu 20.04 machine (or -- what version of ROS 2 are you running on your computer)?
Note that [nodes from different ROS 2 versions are not expected to reliably communicate](https://answers.ros.org/question/341372/can-nodes-from-different-ros-2-distributions-communicate-compatibly/).
Note also that the differences in API are called out [here](https://iroboteducation.github.io/create3_docs/api/docking/#docking) and [here](https://iroboteducation.github.io/create3_docs/api/docking/#dock-information). Are you suggesting we should add warnings about matching ROS 2 versions between the robot and other nodes [here](https://iroboteducation.github.io/create3_docs/setup/ubuntu2204/) as well?

**Comment by carTloyal123** [comment]
Hey there, thanks for the quick reply. To be clear, my machine is running Humble on Ubuntu 22.04 while the create3 is running Galactic. 

Yes I think it may be useful to add a note on the Humble and Galactic setup pages about making sure your ROS2 versions match otherwise there may be instability/message mismatches. That would be great but maybe people read all of the docs completely (which I clearly did not do, I apologize) before they get setup. I will say closed for now but feel free to add that note in the ROS2 setup! Thanks and enjoying the platform!

**Comment by shamlian** [comment]
No worries at all, thanks for writing; you're not the first to have this confusion and I suspect you're right! Will add it to my list of things to do.
