### ISSUE TITLE
localization - injecting filtered data back to the create3

### ISSUE THREAD

**Issue by arielc-brillianetor** [iRobotEducation/irobot_create_msgs#8]
Hi,
I want to add localization abilities to my create3, but I want the robot to use the data which I calculate instead of only using the odometer and the imu installed on the robot. 
Is there a way to inject processed data back into the robot so it thinks that it is where I tell it instead of using only it's own localization process?
Thanks a lot for your help,
Ariel

p.s. not sure where this question is supposed to go, I apologize if it's in the wrong place.

**Comment by shamlian** [comment]
Hi there -- "issues" are for problems with the a repository. Questions about using the robot should go in the [discussions forum here](https://github.com/iRobotEducation/create3_docs/discussions).
