### ISSUE TITLE
ros2 humble release

### ISSUE THREAD

**Issue by wep21** [iRobotEducation/irobot_create_msgs#9]
There exists `humble` branch, but it has not been released.

**Comment by wep21** [comment]
@alsora Could you do bloom-release to `humble`?

**Comment by alsora** [comment]
Hi @wep21, we plan to do a release next week.
Note that the Create 3 robot, the Create 3 examples and the Create 3 simulator have not been updated to Humble yet (this will happen, but I don't have a timeline for it at the moment)

**Comment by wep21** [comment]
@alsora Thank you for letting me know it. I'm looking forward to the release.

**Comment by alsora** [comment]
@gy2256 and @wep21 we just submitted a PR to release the irobot_create_msgs 2.1.0 for ROS 2 Humble.

It will be available at the next Debian packages sync.

**IMPORTANT: the `humble` branch version 2.1.0 and the `main` branch both contain an API break with respect to `galactic`. The `DockServo` action type has been renamed `Dock` and the `Dock` message type has been renamed `DockStatus`.
This API break requires that the robot is running a ROS 2 Humble firmware.
We plan to release a beta version by the end of this month.
Alternatively, you can always build this repository from sources from version 2.0.0**

**Comment by gy2256** [comment]
@alsora Great! Thanks for the update.

**Comment by shamlian** [comment]
Closing this issue since the package has been available for some time.
